INSERT INTO users (name, age) VALUES ("Bill", 20);
INSERT INTO users (name, age) VALUES ("Will", 20);
INSERT INTO users (name, age) VALUES ("Till", 20);
INSERT INTO users (name, age) VALUES ("Cill", 20);
INSERT INTO users (name, age) VALUES ("Dill", 20);
INSERT INTO users (name, age) VALUES ("Fill", 21);
INSERT INTO users (name, age) VALUES ("Gill", 21);
INSERT INTO users (name, age) VALUES ("Hill", 21);
INSERT INTO users (name, age) VALUES ("Jill", 21);
INSERT INTO users (name, age) VALUES ("Kill", 21);
INSERT INTO users (name, age) VALUES ("Lill", 22);
INSERT INTO users (name, age) VALUES ("Mill", 22);
INSERT INTO users (name, age) VALUES ("Nill", 22);
INSERT INTO users (name, age) VALUES ("Oill", 22);
INSERT INTO users (name, age) VALUES ("Pill", 22);
INSERT INTO users (name, age) VALUES ("Qill", 23);
INSERT INTO users (name, age) VALUES ("Rill", 23);
INSERT INTO users (name, age) VALUES ("Sill", 23);
INSERT INTO users (name, age) VALUES ("Vill", 23);
INSERT INTO users (name, age) VALUES ("Yill", 23);

INSERT INTO projects (title) VALUES (null);
INSERT INTO projects (title) VALUES (null);
INSERT INTO projects (title) VALUES (null);
INSERT INTO projects (title) VALUES (null);
INSERT INTO projects (title) VALUES (null);
INSERT INTO projects (title) VALUES (null);
INSERT INTO projects (title) VALUES (null);
INSERT INTO projects (title) VALUES (null);
INSERT INTO projects (title) VALUES (null);
INSERT INTO projects (title) VALUES (null);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,1,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,2,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,2,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,2,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,2,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,2,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,3,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,3,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,3,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,3,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,3,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,4,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,4,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,4,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,4,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,4,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,5,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,5,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,5,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,5,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,5,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,6,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,6,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,6,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,6,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,6,5);


